#ddev-generated
services:
    imgproxy:
        container_name: ddev-${DDEV_SITENAME}-imgproxy
        hostname: ${DDEV_SITENAME}-imgproxy
        image: darthsim/imgproxy:latest
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        networks: [default, ddev_default]
        environment:
            IMGPROXY_BASE_URL: http://web:80
            IMGPROXY_ALLOW_ORIGIN: "*"
        ports:
            - "8081:8080"
        volumes:
            - "imgproxy-cache:/imgproxy/cache"

volumes:
    imgproxy-cache: